"""Updated application to use models.py

Revision ID: 6c4a2cd8b1ea
Revises: 5e92878a92e8
Create Date: 2025-01-21 22:35:10.940484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4a2cd8b1ea'
down_revision = '5e92878a92e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('glass_type', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alcohol_type', sa.String(length=50), nullable=True),
    sa.Column('taste', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('drink_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drink_name', sa.String(length=100), nullable=False),
    sa.Column('ingredient_name', sa.String(length=100), nullable=False),
    sa.Column('measurement_oz', sa.String(length=50), nullable=True),
    sa.Column('measurement_ml', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drink_name'], ['drinks.name'], ),
    sa.ForeignKeyConstraint(['ingredient_name'], ['ingredients.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('glass_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alcohol_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('taste', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('measurements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('volume_ml', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='drink_pkey'),
    sa.UniqueConstraint('name', name='drink_name_key')
    )
    op.drop_table('drink_ingredients')
    op.drop_table('ingredients')
    op.drop_table('drinks')
    # ### end Alembic commands ###
